PROTOS = $(wildcard dataplane/proto/sai/*.proto)
PROTO_SRC = $(patsubst dataplane/proto/sai/%.proto, dataplane/proto/sai/%.pb.cc, $(PROTOS))
PROTO_GRPC_SRC = $(patsubst dataplane/proto/sai/%.proto, dataplane/proto/sai/%.grpc.pb.cc, $(PROTOS))
PROTO_OBJ = $(patsubst dataplane/proto/sai/%.proto, dataplane/proto/sai/%.pb.o, $(PROTOS))
GRPC_OBJ = $(patsubst dataplane/proto/sai/%.proto, dataplane/proto/sai/%.grpc.pb.o, $(PROTOS))
SAI_SRC = $(wildcard dataplane/standalone/sai/*.cc)
SAI_OBJ = $(patsubst dataplane/standalone/sai/%.cc, dataplane/standalone/sai/%.o, $(SAI_SRC))

LEMMING_SRC_DIR := $(CURDIR)/lemming
LUCIUS_BAZEL_TARGET := //dataplane/standalone/lucius:lucius

.PHONY: lucius-bin
lucius-bin:
	cd $(LEMMING_SRC_DIR) && bazel build $(LUCIUS_BAZEL_TARGET)

all: lucius-libsai-trixie

$(PROTO_SRC) $(PROTO_GRPC_SRC) &:
	protoc dataplane/proto/sai/*.proto --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` --experimental_allow_proto3_optional

dataplane/proto/sai/%.pb.o: dataplane/proto/sai/%.pb.cc
	g++ -fPIC -c $< -I . -o $@

dataplane/proto/sai/%.grpc.pb.o:  dataplane/proto/sai/%.grpc.pb.cc
	g++ -fPIC -c $< -I . -o $@

dataplane/standalone/sai/%.o: dataplane/standalone/sai/%.cc $(PROTO_SRC)
	g++ -fPIC -c $< -o $@ -I . -I external/com_github_opencomputeproject_sai -I external/com_github_opencomputeproject_sai/inc  -I external/com_github_opencomputeproject_sai/experimental

protos: $(PROTO_OBJ)
grpc: $(GRPC_OBJ)

# Add entrypoint.o to the objects
ENTRYPOINT_OBJ = entrypoint.o

# Add a rule to compile it separately
$(ENTRYPOINT_OBJ): entrypoint.cc $(PROTO_SRC)
	g++ -fPIC -c entrypoint.cc -o $@ -I . -I external/com_github_opencomputeproject_sai -I external/com_github_opencomputeproject_sai/inc -I external/com_github_opencomputeproject_sai/experimental

libsai.so: $(PROTO_OBJ) $(GRPC_OBJ) $(SAI_OBJ) $(ENTRYPOINT_OBJ)
	g++ -fPIC -o libsai.so -shared $(ENTRYPOINT_OBJ) dataplane/proto/sai/*.o dataplane/standalone/sai/*.o -lglog -lprotobuf -lgrpc++ -I . -I external/com_github_opencomputeproject_sai -I external/com_github_opencomputeproject_sai/inc -I external/com_github_opencomputeproject_sai/experimental

lucius-libsai-trixie:
# Wait for docker daemon to come up. Takes 30-45 seconds in trixie
	@wait_for_docker=0; \
	while [ $$wait_for_docker -lt 40 ]; do \
		docker info >/dev/null 2>&1 && break; \
		sleep 3; \
		wait_for_docker=$$((wait_for_docker + 1)); \
	done; \
	echo "Wait of $$((wait_for_docker * 3)) seconds for docker"; \

	DOCKER_BUILDKIT=1 docker build . -f Dockerfile.saibuilder -t lemming-libsai:latest
	docker create --name libsai-temp lemming-libsai:latest
	docker cp libsai-temp:/build/libsai.so ./libsai.so
	docker rm libsai-temp

install: lucius-libsai-trixie
	echo "Inside lucius_sai"
	install -D ./libsai.so $(DESTDIR)/usr/lib/x86_64-linux-gnu/libsaivs.so.0.0.0
	cd $(DESTDIR)/usr/lib/x86_64-linux-gnu && ln -s libsaivs.so.0.0.0 libsaivs.so.0

clean:
	-rm -f dataplane/proto/sai/*.cc dataplane/proto/sai/*.h dataplane/proto/sai/*.o
	-rm -f dataplane/standalone/sai/*.o
	-rm -f libsai.so

.PHONY: clean install
